export const START_AUTH = 'START_AUTH';
export const SUCCESSFUL_AUTH = 'SUCCESSFUL_AUTH';
export const ERROR_AUTH = 'ERROR_AUTH';
export const LOGOUT = 'LOGOUT';

export const START_LOADING_REV_GEO = "START_LOADING_REV_GEO";
export const SUCCESSFUL_LOADING_REV_GEO = "SUCCESSFUL_LOADING_REV_GEO ";
export const LOADING_ERROR_REV_GEO = "LOADING_ERROR_REV_GEO";

export const START_LOADING_EVENTS = 'START_LOADING_EVENTS';
export const SUCCESSFUL_LOADING_EVENTS = 'SUCCESSFUL_LOADING_EVENTS';
export const LOADING_ERROR_EVENTS = 'LOADING_ERROR_EVENTS';

export const GET_ONE_EVENT = "GET_ONE_EVENT";
export const EDIT_EVENT = "EDIT_EVENT";
export const ADD_EVENT = "ADD_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const ERROR_EVENT = "ERROR_EVENT";

export const GET_EVENT_PHOTOS = "GET_EVENT_PHOTOS";
export const GET_ONE_PHOTO = "GET_ONE_PHOTO";
export const EDIT_ONE_PHOTO = "EDIT_ONE_PHOTO";
export const ADD_PHOTO = "ADD_PHOTO";
export const DELETE_PHOTO = "DELETE_PHOTO";
export const ERROR_PHOTO = "ERROR_PHOTO";

export const SET_CURRENT_COORDINATES = "SET_CURRENT_COORDINATES";
export const SET_CREATE_EVENT_WINDOW_VISIBLE = "SET_CREATE_EVENT_WINDOW_VISIBLE";
export const SET_CURRENT_EVENT = "SET_CURRENT_EVENT";

export const SET_SEARCH_POSITION = "SET_SEARCH_POSITION";
export const SET_USER_POSITION = "SET_USER_POSITION";

